encoding: "utf-8"
permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]

paginate: 10
paginate_path: ":num"

baseurl: ""

title: "指间风雨"
email: "zkl_1011@126.com"
description: "Developer"
github_username:  "kongliangzhong"

#url: "http://jcloudnote.com"
#imgrepo: "http://jcloudnote.com/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

